/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.capibarashop.swing.panel;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Angel Aimar
 */
public class P_AplicacionCliente extends javax.swing.JPanel {

    private P_CarritoVentas carritoVentasPanel;
    
    
    private CardLayout cardLayout;
    /**
     * Creates new form P_ProductosCliente
     */
    public P_AplicacionCliente() throws SQLException {
        initComponents();
        iniciarVistas();
    }
    
    public P_CarritoVentas getCarritoVentasPanel(){
        return carritoVentasPanel;
    }
    
    private void iniciarVistas() {
        cardLayout = new CardLayout();
        jPPantalla.setLayout(cardLayout);

        try {
            jPPantalla.add(new P_ProductosCliente(), "inicio");
        } catch (Exception e) {
            e.printStackTrace();
            jPPantalla.add(new JLabel("Error al cargar inicio"), "inicio");
        }
        
        carritoVentasPanel = new P_CarritoVentas();
        
        jPPantalla.add(carritoVentasPanel, "carrito");
        jPPantalla.add(new P_MiCuenta(), "micuenta");

        cardLayout.show(jPPantalla, "inicio");
        jPPerfilOpciones.setVisible(false);
    }
    
//    public void recargarCarrito() {
//        cargarProductosDelCarrito(); // Método que ya tienes
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPPantalla = new javax.swing.JPanel();
        jPOpciones = new javax.swing.JPanel();
        jLCarrito = new javax.swing.JLabel();
        jLInicio = new javax.swing.JLabel();
        jLPerfil = new javax.swing.JLabel();
        jPPerfilOpciones = new javax.swing.JPanel();
        jLMiCuenta = new javax.swing.JLabel();
        jLMisPedidos = new javax.swing.JLabel();
        jLCerrarSesion = new javax.swing.JLabel();

        jPPantalla.setBackground(new java.awt.Color(255, 153, 153));
        jPPantalla.setPreferredSize(new java.awt.Dimension(670, 500));
        jPPantalla.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPPantalla.setLayout(new CardLayout());

        jPOpciones.setBackground(new java.awt.Color(255, 0, 153));
        jPOpciones.setForeground(new java.awt.Color(255, 0, 153));
        jPOpciones.setMaximumSize(new java.awt.Dimension(360, 110));
        jPOpciones.setMinimumSize(new java.awt.Dimension(360, 110));
        jPOpciones.setName(""); // NOI18N
        jPOpciones.setPreferredSize(new java.awt.Dimension(360, 110));
        jPOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCarrito.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLCarrito.setForeground(new java.awt.Color(0, 0, 0));
        jLCarrito.setText("Carrito");
        jLCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCarritoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCarritoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCarritoMouseExited(evt);
            }
        });
        jPOpciones.add(jLCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 6, -1, -1));

        jLInicio.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLInicio.setForeground(new java.awt.Color(0, 0, 0));
        jLInicio.setText("Inicio");
        jLInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLInicioMouseExited(evt);
            }
        });
        jPOpciones.add(jLInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 6, -1, -1));

        jLPerfil.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLPerfil.setForeground(new java.awt.Color(0, 0, 0));
        jLPerfil.setText("Hola Usuario ■");
        jLPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLPerfilMouseExited(evt);
            }
        });
        jPOpciones.add(jLPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 6, -1, -1));

        jPPerfilOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPPerfilOpcionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPPerfilOpcionesMouseExited(evt);
            }
        });

        jLMiCuenta.setText("Mi Cuenta");
        jLMiCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMiCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMiCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMiCuentaMouseExited(evt);
            }
        });

        jLMisPedidos.setText("Mis Pedidos");
        jLMisPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLMisPedidosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLMisPedidosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLMisPedidosMouseExited(evt);
            }
        });

        jLCerrarSesion.setText("Cerrar Sesión");
        jLCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPPerfilOpcionesLayout = new javax.swing.GroupLayout(jPPerfilOpciones);
        jPPerfilOpciones.setLayout(jPPerfilOpcionesLayout);
        jPPerfilOpcionesLayout.setHorizontalGroup(
            jPPerfilOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPerfilOpcionesLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jPPerfilOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLMiCuenta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLMisPedidos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPPerfilOpcionesLayout.setVerticalGroup(
            jPPerfilOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPerfilOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLMiCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMisPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPOpciones.add(jPPerfilOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 32, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCarritoMouseClicked
        if(carritoVentasPanel != null){
            carritoVentasPanel.recargarCarrito();
        }
        
        cardLayout.show(jPPantalla, "carrito");
        
    }//GEN-LAST:event_jLCarritoMouseClicked

    private void jLCarritoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCarritoMouseEntered
        // TODO add your handling code here:
        
        jLCarrito.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLCarrito.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLCarritoMouseEntered

    private void jLCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCarritoMouseExited
        // TODO add your handling code here:
        jLCarrito.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLCarrito.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jLCarritoMouseExited

    private void jLInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInicioMouseClicked
        // TODO add your handling code here:
        cardLayout.show(jPPantalla, "inicio");
    }//GEN-LAST:event_jLInicioMouseClicked

    private void jLInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInicioMouseEntered
        // TODO add your handling code here:
        jLInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLInicio.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLInicioMouseEntered

    private void jLInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInicioMouseExited
        // TODO add your handling code here:
        jLInicio.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLInicio.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLInicioMouseExited

    private void jLPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPerfilMouseClicked
        // TODO add your handling code here:
        
        int confirm = JOptionPane.showConfirmDialog(null, "¿Cerrar sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(P_AplicacionCliente.this);
            frame.dispose();
            new P_Login().setVisible(true);
        }
        
    }//GEN-LAST:event_jLPerfilMouseClicked

    private void jLPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPerfilMouseEntered
        // TODO add your handling code here:
        jLPerfil.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLPerfil.setForeground(Color.WHITE);
        jPPerfilOpciones.setVisible(true);
    }//GEN-LAST:event_jLPerfilMouseEntered

    private void jLPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLPerfilMouseExited
        // TODO add your handling code here:
            new javax.swing.Timer(150, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Point mouse = MouseInfo.getPointerInfo().getLocation();
                SwingUtilities.convertPointFromScreen(mouse, jPPerfilOpciones);
                if (!jPPerfilOpciones.contains(mouse)) {
                    jPPerfilOpciones.setVisible(false);
                    jLPerfil.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    jLPerfil.setForeground(Color.BLACK);
                }
            }
        }) {{
            setRepeats(false);
        }}.start();
    }//GEN-LAST:event_jLPerfilMouseExited

    private void jPPerfilOpcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPPerfilOpcionesMouseEntered
        // TODO add your handling code here:
        jPPerfilOpciones.setVisible(true);
    }//GEN-LAST:event_jPPerfilOpcionesMouseEntered

    private void jPPerfilOpcionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPPerfilOpcionesMouseExited
        // TODO add your handling code here:
        Point mouse = MouseInfo.getPointerInfo().getLocation();
        SwingUtilities.convertPointFromScreen(mouse, jPPerfilOpciones);

        if (!jPPerfilOpciones.contains(mouse)) {
            jPPerfilOpciones.setVisible(false);
        }
        
        jLPerfil.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLPerfil.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_jPPerfilOpcionesMouseExited

    private void jLMiCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMiCuentaMouseClicked
        // TODO add your handling code here:
        cardLayout.show(jPPantalla, "micuenta");
        jPPerfilOpciones.setVisible(false);
        
    }//GEN-LAST:event_jLMiCuentaMouseClicked

    private void jLMiCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMiCuentaMouseEntered
        // TODO add your handling code here:
        jLMiCuenta.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLMiCuenta.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLMiCuentaMouseEntered

    private void jLMisPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMisPedidosMouseClicked
        // TODO add your handling code here:
        jPPerfilOpciones.setVisible(false);
    }//GEN-LAST:event_jLMisPedidosMouseClicked

    private void jLMisPedidosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMisPedidosMouseEntered
        // TODO add your handling code here:
        jLMisPedidos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLMisPedidos.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLMisPedidosMouseEntered

    private void jLMisPedidosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMisPedidosMouseExited
        // TODO add your handling code here:
        jLMisPedidos.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLMisPedidos.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLMisPedidosMouseExited

    private void jLCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarSesionMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "¿Cerrar sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(P_AplicacionCliente.this);
            frame.dispose();
            new P_Login().setVisible(true);
        }
        jLPerfil.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLPerfil.setForeground(Color.BLACK);
        jPPerfilOpciones.setVisible(false); // También ocultamos aquí
    }//GEN-LAST:event_jLCerrarSesionMouseClicked

    private void jLCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarSesionMouseEntered
        // TODO add your handling code here:
        jLCerrarSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLCerrarSesion.setForeground(Color.RED);
    }//GEN-LAST:event_jLCerrarSesionMouseEntered

    private void jLMiCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLMiCuentaMouseExited
        // TODO add your handling code here:
        jLMiCuenta.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLMiCuenta.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLMiCuentaMouseExited

    private void jLCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarSesionMouseExited
        // TODO add your handling code here:
        jLCerrarSesion.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLCerrarSesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLCerrarSesionMouseExited

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCarrito;
    private javax.swing.JLabel jLCerrarSesion;
    private javax.swing.JLabel jLInicio;
    private javax.swing.JLabel jLMiCuenta;
    private javax.swing.JLabel jLMisPedidos;
    private javax.swing.JLabel jLPerfil;
    private javax.swing.JPanel jPOpciones;
    private javax.swing.JPanel jPPantalla;
    private javax.swing.JPanel jPPerfilOpciones;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
