/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.capibarashop.swing.panel;

import com.capibarashop.clases.DetalleCarrito;
import com.capibarashop.clases.Direccion;
import com.capibarashop.clases.Producto;
import com.capibarashop.clases.Usuario;
import com.capibarashop.clases.dao.VentaDAO;
import com.capibarashop.dialogs.direccion.DialogSeleccionarDireccion;
import com.capibarashop.clases.Utilidades;
import com.capibarashop.clases.Carrito;
import com.capibarashop.clases.MetodoPago;
import com.capibarashop.clases.dao.CarritoDAO;
import com.capibarashop.clases.dao.DatosFacturacionDAO;
import com.capibarashop.clases.DatosFacturacion;
import com.capibarashop.clases.dao.DetalleCarritoDAO;
import com.capibarashop.clases.dao.DireccionDAO;
import com.capibarashop.clases.dao.MetodosPagoDAO;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.math.BigDecimal;
import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Angel Aimar
 */
public class P_CarritoVentas extends javax.swing.JPanel {
    
    
    private P_CarritoVentas panelCarrito;
    Utilidades u = new Utilidades();
    private int idCarrito;
    private DefaultTableModel modelo;
    Direccion direccion;
    /**
     * Creates new form P_CarritoVentas
     */
    public P_CarritoVentas() {
        initComponents();
        DireccionDAO dao = new DireccionDAO();
        
        direccion = dao.obtenerDireccionPrincipal(Usuario.getUsuarioActual().getId());
        
        if (direccion != null) {
            lblDireccionEntrega.setText(direccion.toString());
        } else {
            lblDireccionEntrega.setText("No hay dirección seleccionada");
        }
        
        
        prepararTabla();
        idCarrito = obtenerIdCarritoActivo();
        cargarProductosDelCarrito();
        cargarMetodosDePago();
    }
    
    private void cargarMetodosDePago(){
        List<MetodoPago> metodos = new MetodosPagoDAO().obtenerTodos();
        MetodoPago metodoInicial = new MetodoPago(0, "Selecciona una opción", "");

        Utilidades.cargarJComboBox(
            jCBMetodoPago,
            metodos,
            metodoInicial,
            Comparator.comparing(MetodoPago :: getNombre),
            "Selecciona una opción"
        );
    }
    
    private int obtenerIdCarritoActivo() {
        CarritoDAO dao = new CarritoDAO();
        return dao.obtenerCarritoActivoID(Usuario.getUsuarioActual().getId());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSPTabla = new javax.swing.JScrollPane();
        jTCarrito = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTTotal = new javax.swing.JTable();
        jBPago = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDireccionEntrega = new javax.swing.JLabel();
        jCBMetodoPago = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.setBackground(new java.awt.Color(241, 184, 184));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Carrito");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTCarrito.setBackground(new java.awt.Color(255, 255, 255));
        jTCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTCarrito.setPreferredSize(new java.awt.Dimension(670, 20));
        jSPTabla.setViewportView(jTCarrito);

        jPanel1.add(jSPTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 670, 530));

        JTTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total"
            }
        ));
        jScrollPane3.setViewportView(JTTotal);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 170, 140));

        jBPago.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBPago.setText("Pagar");
        jBPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPagoActionPerformed(evt);
            }
        });
        jPanel1.add(jBPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dirección de Entrega:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        lblDireccionEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccionEntrega.setForeground(new java.awt.Color(0, 0, 0));
        lblDireccionEntrega.setText("lblDireccionEntrega");
        jPanel1.add(lblDireccionEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 170, 140));

        jCBMetodoPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jCBMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Metodo de Pago:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTotalGeneral() {
        double total = 0.0;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String subtotalStr = modelo.getValueAt(i, 4).toString().replace("$", "");
            total += Double.parseDouble(subtotalStr);
        }

        DefaultTableModel modeloTotales = (DefaultTableModel) JTTotal.getModel();
        modeloTotales.setRowCount(0);
        modeloTotales.addRow(new Object[]{String.format("$%.2f", total)});
    }
    
    private void jBPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPagoActionPerformed
        DireccionDAO dao = new DireccionDAO();
    
        MetodoPago metodoSeleccionado = (MetodoPago) jCBMetodoPago.getSelectedItem();
        
        if (metodoSeleccionado == null || metodoSeleccionado.getId() == 0) {
            u.generarMensajeGenerico(this, Utilidades.FALTAN_CAMPOS,
                            "¡Selecciona un metodo de pago!",
                            "No se ha seleccionado ningun metodo de pago",
                            "Metodo de pago", JOptionPane.INFORMATION_MESSAGE, 150, 150);
            return;
        }
        
        // Validar dirección actual o seleccionar una nueva
        if (direccion != null) {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "¿Deseas usar la dirección actual?\n\n" + direccion.toString().replaceAll("<[^>]*>", ""),
                    "Confirmar dirección",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (respuesta == JOptionPane.NO_OPTION) {
                DialogSeleccionarDireccion dialog = new DialogSeleccionarDireccion(null, true);
                dialog.setVisible(true);

                Direccion nuevaDireccion = Usuario.getUsuarioActual().getDireccionSeleccionada();
                if (nuevaDireccion != null) {
                    direccion = nuevaDireccion;
                    lblDireccionEntrega.setText(direccion.toString());
                    dao.marcarComoPrincipal(direccion.getId(), Usuario.getUsuarioActual().getId());
                } else {
                    u.generarMensajeGenerico(this, Utilidades.FALTAN_CAMPOS,
                            "¡Falta la Dirección!",
                            "No se seleccionó una Dirección\nSino ¿Cómo te llegará tu paquete?",
                            "Dirección", JOptionPane.INFORMATION_MESSAGE, 150, 150);
                    return;
                }
            }
        } else {
            DialogSeleccionarDireccion dialog = new DialogSeleccionarDireccion(null, true);
            dialog.setVisible(true);

            Direccion nuevaDireccion = Usuario.getUsuarioActual().getDireccionSeleccionada();
            if (nuevaDireccion != null) {
                direccion = nuevaDireccion;
                lblDireccionEntrega.setText(direccion.toString());
                dao.marcarComoPrincipal(direccion.getId(), Usuario.getUsuarioActual().getId());
            } else {
                u.generarMensajeGenerico(this, Utilidades.FALTAN_CAMPOS,
                        "¡Falta la Dirección!",
                        "No se seleccionó una Dirección\nSino ¿Cómo te llegará tu paquete?",
                        "Dirección", JOptionPane.INFORMATION_MESSAGE, 150, 150);
                return;
            }
        }

        // Generar resumen visual
        String total = JTTotal.getValueAt(0, 0).toString();
        StringBuilder resumen = new StringBuilder("<html><h2>Resumen de Compra</h2><ul>");
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nombre = modelo.getValueAt(i, 1).toString();
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 2).toString());
            String precio = modelo.getValueAt(i, 3).toString();
            resumen.append(String.format("<li>%s x%d - %s</li>", nombre, cantidad, precio));
        }
        resumen.append("</ul>");
        resumen.append("<p><b>Total:</b> ").append(total).append("</p>");
        resumen.append("<p><b>Dirección:</b> ").append(direccion.toString().replaceAll("<[^>]*>", "")).append("</p>");
        resumen.append("</html>");

        int confirmacion = JOptionPane.showConfirmDialog(this, new JLabel(resumen.toString()),
                "¿Confirmas tu compra?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmacion != JOptionPane.YES_OPTION) return;

        // Si requiere factura, obtener datos fiscales
        DatosFacturacion datosFacturacion = null;
        if (direccion.getTipo().getNombre().equalsIgnoreCase("factura")) {
            DatosFacturacionDAO dfDao = new DatosFacturacionDAO();
            datosFacturacion = dfDao.obtenerPorUsuario(Usuario.getUsuarioActual().getId());

            if (datosFacturacion == null) {
                u.generarMensajeGenerico(this, Utilidades.FALTAN_CAMPOS,
                        "Datos fiscales faltantes",
                        "No se encontraron datos fiscales para el usuario.\nDebes registrar tu RFC y razón social para emitir la factura.",
                        "Datos Fiscales", JOptionPane.WARNING_MESSAGE, 150, 150);
                return;
            }
        }
        
        // Realizar venta con o sin factura
        VentaDAO ventaDAO = new VentaDAO();
        boolean exito = ventaDAO.realizarVenta(idCarrito, Usuario.getUsuarioActual().getId(), datosFacturacion, metodoSeleccionado);
        
        if (exito) {
            new CarritoDAO().cerrarCarrito(idCarrito);

            String mensaje = (datosFacturacion != null) ? "Factura generada" : "Compra realizada";
            String detalle = (datosFacturacion != null)
                    ? "Tu compra y factura han sido realizadas exitosamente."
                    : "Tu compra se ha realizado con éxito.";

            u.generarMensajeGenerico(this, Utilidades.EXITO_PROCESO_GENERICO,
                    mensaje, detalle, mensaje, JOptionPane.INFORMATION_MESSAGE, 150, 150);

            modelo.setRowCount(0);
            actualizarTotalGeneral();
            lblDireccionEntrega.setText(direccion.toString());
        } else {
            u.generarMensajeGenerico(this, Utilidades.ERROR_FALLO,
                    "¡Hubo un error inesperado!",
                    "Tu compra no se pudo realizar.",
                    "Compra no realizada", JOptionPane.ERROR_MESSAGE, 150, 150);
        }
    }//GEN-LAST:event_jBPagoActionPerformed

    private void cargarProductosDelCarrito() {
        modelo.setRowCount(0); // Limpia la tabla
        BigDecimal total = BigDecimal.ZERO;
        
        int idUsuario = Usuario.getUsuarioActual().getId();
        CarritoDAO carritoDAO = new CarritoDAO();
        Carrito carrito = carritoDAO.obtenerCarritoActivo(idUsuario);
        
        if(carrito != null){
            
            DetalleCarritoDAO dao = new DetalleCarritoDAO();
            List<DetalleCarrito> lista = dao.obtenerDetalles(idCarrito);

            for (DetalleCarrito detalle : lista) {
                Producto producto = detalle.getProducto();

                if (producto != null) {
                    int cantidad = detalle.getCantidad();
                    BigDecimal precio = producto.getPrecio();
                    BigDecimal subtotal = precio.multiply(BigDecimal.valueOf(cantidad));

                    // Escalar imagen (si existe)
                    ImageIcon icono = null;
                    if (producto.getImagen() != null) {
                        Image imagenEscalada = new ImageIcon(producto.getImagen()).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                        icono = new ImageIcon(imagenEscalada);
                    }

                    modelo.addRow(new Object[]{
                        icono, // Imagen renderizada
                        producto.getNombre(),
                        cantidad,
                        String.format("$%.2f", precio),
                        String.format("$%.2f", subtotal)
                    });

                    total = total.add(subtotal);
                } else {
                    System.err.println("Producto nulo en DetalleCarrito.");
                }
            }
        }
        else{
            System.out.println("No hay carrito activo para este usuario.");
        }
        
        

        // Actualiza el total
        DefaultTableModel modeloTotales = (DefaultTableModel) JTTotal.getModel();
        modeloTotales.setRowCount(0);
        modeloTotales.addRow(new Object[]{String.format("$%.2f", total)});
    }
    
    public void recargarCarrito(){
        cargarProductosDelCarrito();
    }
    
    private void prepararTabla(){
        modelo = new DefaultTableModel(
            new Object[]{"Imagen", "Nombre", "Cantidad", "Precio", "Subtotal"}, 0
        );
        jTCarrito.setModel(modelo);

        jTCarrito.setFillsViewportHeight(true);
        jTCarrito.setShowGrid(true);
        jTCarrito.setGridColor(Color.LIGHT_GRAY);
        
        jTCarrito.setRowHeight(60);
        
        // Renderizador para la columna de imagen
        jTCarrito.getColumnModel().getColumn(0).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                if (value instanceof ImageIcon imageIcon) {
                    setIcon(imageIcon);
                    setText(""); 
                } else {
                    setIcon(null);
                    setText(value != null ? value.toString() : "");
                }
                return this;
            }
        });

        // Renderizador centrado para columnas de texto (del 1 al 4) — ¡UNO DIFERENTE POR COLUMNA!
        for (int i = 1; i <= 4; i++) {
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            jTCarrito.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        
        
        
        // Tamaños explícitos para evitar que las columnas colapsen
        jTCarrito.getColumnModel().getColumn(0).setPreferredWidth(60);   // Foto
        jTCarrito.getColumnModel().getColumn(1).setPreferredWidth(200);  // Nombre
        jTCarrito.getColumnModel().getColumn(2).setPreferredWidth(80);   // Cantidad
        jTCarrito.getColumnModel().getColumn(3).setPreferredWidth(100);  // Precio
        jTCarrito.getColumnModel().getColumn(4).setPreferredWidth(120);  // Subtotal

        jTCarrito.setRowHeight(60); // Para que las imágenes se vean bien

        modelo.addTableModelListener(e -> {
            if (e.getColumn() == 2) {
                int fila = e.getFirstRow();
                int cantidad = (int) modelo.getValueAt(fila, 2);
                double precioUnitario = Double.parseDouble(modelo.getValueAt(fila, 3).toString().replace("$", ""));
                double subtotal = cantidad * precioUnitario;

                modelo.setValueAt(String.format("$%.2f", subtotal), fila, 4);
                actualizarTotalGeneral();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTTotal;
    private javax.swing.JButton jBPago;
    private javax.swing.JComboBox<MetodoPago> jCBMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jSPTabla;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTCarrito;
    private javax.swing.JLabel lblDireccionEntrega;
    // End of variables declaration//GEN-END:variables
}
