/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.capibarashop.swing.panel;

import com.capibarashop.clases.Producto;
import com.capibarashop.clases.dao.ProductoDAO;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author Angel Aimar
 */
public class P_ProductosCliente extends javax.swing.JPanel {

    /**
     * Creates new form P_ProductosCliente
     * @throws java.sql.SQLException
     */
    public P_ProductosCliente() throws SQLException {
        initComponents();
        contenedorProductos.setLayout(new GridLayout(0, 2, 10, 10));
        List<Producto> productos = new ProductoDAO().listarProductosParaClientes();
        cargarProductos(productos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollProductos = new javax.swing.JScrollPane();
        contenedorProductos = new javax.swing.JPanel();

        scrollProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contenedorProductos.setOpaque(false);
        contenedorProductos.setLayout(new java.awt.GridLayout());
        scrollProductos.setViewportView(contenedorProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(scrollProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        scrollProductos.getVerticalScrollBar().setUnitIncrement(20);
    }// </editor-fold>//GEN-END:initComponents

    public void cargarProductos(List<Producto> listaProductos) {
        contenedorProductos.removeAll();  // Limpia anteriores
        for (Producto p : listaProductos) {
            P_ProductoItem item = new P_ProductoItem();
            item.setDatosProducto(p);
            contenedorProductos.add(item);
        }
        contenedorProductos.revalidate();
        contenedorProductos.repaint();
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorProductos;
    private javax.swing.JScrollPane scrollProductos;
    // End of variables declaration//GEN-END:variables
}
