/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs.producto;

import com.capibarashop.clases.Producto;
import com.capibarashop.clases.dao.ProductoDAO;
import com.capibarashop.clases.Usuario;
import com.capibarashop.clases.Utilidades;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Angel Aimar
 */
public class DialogEliminarProducto extends javax.swing.JDialog {
    
    private Utilidades u = new Utilidades();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogEliminarProducto.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     */
    public DialogEliminarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource(Utilidades.ELIMINAR_PRODUCTO));
        Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        jLCapibara.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jSIdProducto = new javax.swing.JSpinner();
        jBBuscar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Eliminar Producto");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 190, -1));

        jLNombre.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre.setText("ID:");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 162, -1, -1));

        jBBuscar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, -1));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 120, 120));
        jPanel1.add(jSIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, -1));
        jSIdProducto.setModel(new SpinnerNumberModel(0, 0, 999999, 1));

        jBBuscar1.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        jBBuscar1.setText("Cancelar");
        jBBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 230, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        int id = (Integer) jSIdProducto.getValue();
        
        Producto p;
        
        ProductoDAO dao = new ProductoDAO();
        p = dao.buscarProductoIDVendedores(id);
        
        if (p == null) {
            u.generarMensajeGenerico(this, Utilidades.PRODUCTO_NO_ENCONTRADO,
                    "¡El producto de ID: " + id + " no existe o no se encontró!",
                    "No se encontró ningun producto con ese ID, vuelve a intentarlo o verifica bien los IDs de tus productos existentes",
                    "Buscar Producto", JOptionPane.INFORMATION_MESSAGE, 120, 120);
            return;
        }
        
        String imagenURL = u.guardarImagenTemporal(p.getImagen(), p.getId());
        
        if(imagenURL == null){
            imagenURL = "";
        }
        
        String mensaje = String.format("""
            <html>
              <head>
                <style>
                  body { font-family: Arial, sans-serif; }
                        h3 { color: #5D3FD3; margin-top: 0; }
                        table {
                          width: 100%%;
                          border-collapse: collapse;
                          margin-top: 10px;
                        }
                        td {
                          padding: 5px;
                          border: 1px solid #ccc;
                          vertical-align: top;
                        }
                        td:first-child {
                          font-weight: bold;
                          background-color: #f0f0f0;
                          width: 100px;
                        }
                        .desc {
                          max-height: 100px;
                          overflow-y: auto;
                        }
                </style>
              </head>
              <body>
                <h3>¿Deseas eliminar el siguiente producto?</h3>
                <table>
                  <tr><td>ID:</td><td>%d</td></tr>
                  <tr><td>Nombre:</td><td>%s</td></tr>
                  <tr><td>Precio:</td><td>$%.2f</td></tr>
                  <tr><td>Stock:</td><td>%d</td></tr>
                  <tr><td>Descripción:</td><td class="desc">%s</td></tr>
                  <tr><td>Imagen:</td><td><img src="%s" width="100" height="100"/></td></tr>
                </table>
              </body>
            </html>
            """, 
                p.getId(),
                p.getNombre(),
                p.getPrecio().doubleValue(),
                p.getStock(),
                p.getDescripcion().replace("\n", "<br>"),
                imagenURL
            );
        
        JEditorPane editorPane = new JEditorPane("text/html", mensaje);
        editorPane.setEditable(false);
        editorPane.setCaretPosition(0);

        JScrollPane scrollPane = new JScrollPane(editorPane);
        scrollPane.setPreferredSize(new Dimension(450, 250));
        
        int confirmacion = JOptionPane.showConfirmDialog(this, scrollPane, "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION){
            int confirmacion2 = JOptionPane.showConfirmDialog(this, "Selecciona 'Yes', para continuar con la eliminación", 
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            
            if (confirmacion2 == JOptionPane.YES_OPTION) {
                if (dao.eliminarProducto(p.getId())) {
                    u.generarMensajeGenerico(this, Utilidades.ELIMINAR_PRODUCTO,
                        "¡Producto eliminado exitosamente!",
                        "El Producto " + p.getNombre() + " Ha sido eliminado exitosamente",
                        "Eliminación", JOptionPane.INFORMATION_MESSAGE, 120, 120);
                    this.dispose();
                } else {
                    u.generarMensajeGenerico(this, Utilidades.ERROR_FALLO,
                        "¡Hubo un error inesperado!",
                        "No se pudo eliminar el producto",
                        "Error Inesperado", JOptionPane.ERROR_MESSAGE, 120, 120);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBBuscar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscar1;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSIdProducto;
    // End of variables declaration//GEN-END:variables
}
