/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs.producto;

import com.capibarashop.clases.dao.CategoriaDAO;
import com.capibarashop.clases.Categoria;
import com.capibarashop.clases.Producto;
import com.capibarashop.clases.dao.ProductoDAO;
import com.capibarashop.clases.Usuario;
import com.capibarashop.clases.Utilidades;
import com.capibarashop.swing.ScrollBar;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.JSpinner;
import javax.swing.JFileChooser;
import javax.swing.ScrollPaneConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.nio.file.Files;


/**
 *
 * @author Angel Aimar
 */
public class DialogAgregarProducto extends javax.swing.JDialog {
    
    private Utilidades u = new Utilidades();
    private byte[] imagenSeleccionada;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAgregarProducto.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     * @param parent
     * @param modal
     */
    public DialogAgregarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Utilidades.aplicarScrollCombo(jCBCategoria);
        
        ImageIcon icon = new ImageIcon(getClass().getResource(Utilidades.AGREGAR_PRODUCTO));
        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        jLCapibara.setIcon(new ImageIcon(img));
        
        CategoriaDAO.cargarCategorias(jCBCategoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLCategoria = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLPrecio = new javax.swing.JLabel();
        jLStock = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jCBCategoria = new javax.swing.JComboBox<>();
        jTFNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jBGuardar = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jSStock = new javax.swing.JSpinner();
        jSPrecio = new javax.swing.JSpinner();
        jBCancelar = new javax.swing.JButton();
        jLImagen = new javax.swing.JLabel();
        jLImagenOpcional = new javax.swing.JLabel();
        jLImagenMostrar = new javax.swing.JLabel();
        jBSeleccionarImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Agregar Nuevo Producto");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 260, -1));

        jLCategoria.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jLCategoria.setText("Categoria:");
        jPanel1.add(jLCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLNombre.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre.setText("Nombre:");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLPrecio.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jLPrecio.setText("Precio:");
        jPanel1.add(jLPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLStock.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLStock.setForeground(new java.awt.Color(0, 0, 0));
        jLStock.setText("Stock:");
        jPanel1.add(jLStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLDescripcion.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jLDescripcion.setText("Descripcion:");
        jPanel1.add(jLDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jCBCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jCBCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 230, 30));
        jPanel1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 270, -1));

        jTADescripcion.setColumns(20);
        jTADescripcion.setLineWrap(true);
        jTADescripcion.setRows(5);
        jTADescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTADescripcion);
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 250, 130));

        jBGuardar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 130, -1));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));
        jPanel1.add(jSStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, -1));
        jSStock.setModel(new SpinnerNumberModel(0, 0, 10000, 1));

        jSPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSPrecioFocusLost(evt);
            }
        });
        jPanel1.add(jSPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));
        jSPrecio.setModel(new SpinnerNumberModel(0, 0.00, 999999.99, 0.01));
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(jSPrecio, "$#,##0.00");
        jSPrecio.setEditor(editor);

        jBCancelar.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 110, -1));

        jLImagen.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLImagen.setForeground(new java.awt.Color(0, 0, 0));
        jLImagen.setText("Imagen:");
        jPanel1.add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLImagenOpcional.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLImagenOpcional.setForeground(new java.awt.Color(0, 0, 0));
        jLImagenOpcional.setText("(Opcional)");
        jPanel1.add(jLImagenOpcional, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLImagenMostrar.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLImagenMostrar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLImagenMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 100, 100));

        jBSeleccionarImagen.setText("Seleccionar Imagen");
        jBSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSeleccionarImagenActionPerformed(evt);
            }
        });
        jPanel1.add(jBSeleccionarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        Categoria categoria = (Categoria) jCBCategoria.getSelectedItem();
        String nombre = jTFNombre.getText().trim();
        String descripcion = jTADescripcion.getText().trim();
        Double precio = (Double) jSPrecio.getValue();
        int stock = (Integer) jSStock.getValue();
        
        if (nombre.isEmpty() || descripcion.isEmpty() || precio <= 0.00 || categoria == null || categoria.getId() == 0) {
            StringBuilder errores = new StringBuilder("Corrige los siguientes campos:\n");

            if (nombre.isEmpty()) {
                errores.append("- El nombre es obligatorio.\n");
            }
            
            if (precio <= 0.00) {
                errores.append("- El precio debe ser mayor a $0.00.\n");
            }
            
            if (descripcion.isEmpty()) {
                errores.append("- La descripción es obligatoria.\n");
            }
            
            if (categoria == null || categoria.getId() == 0){
                errores.append("- Selecciona una categoría válida.\n");
            }
            
            if (stock < 0) {
                errores.append("- El stock no puede ser negativo.\n");
            }
            
            u.generarMensajeGenerico(this, Utilidades.FALTAN_CAMPOS,
                    "¡Faltan los siguientes Campos!",
                    errores.toString(),
                    "Agregar Producto", JOptionPane.INFORMATION_MESSAGE, 150, 150);
            return;
        }

        // Continuar si todo es válido
        if (Usuario.getUsuarioActual().getId() != 0) {
            Producto productoNuevo = (imagenSeleccionada != null)
                ? new Producto(nombre, precio, descripcion, stock, imagenSeleccionada, categoria, Usuario.getUsuarioActual())
                : new Producto(nombre, precio, descripcion, stock, categoria, Usuario.getUsuarioActual());
            
            ProductoDAO dao = new ProductoDAO();
            try {
                if (dao.insertarProducto(productoNuevo)) {
                    u.generarMensajeGenerico(this, Utilidades.AGREGAR_PRODUCTO,
                        "¡Se ha agreado un producto con exito!",
                        "El producto " + productoNuevo.getNombre() + " se ha agregado con exito.",
                        "Agregar Producto", JOptionPane.INFORMATION_MESSAGE, 150, 150);
                    dispose();
                } else {
                    u.generarMensajeGenerico(this, Utilidades.ERROR_FALLO,
                        "¡Hubo un error inesperado!",
                        "Revisa que los datos esten bien declarados porque no se Agregó el producto",
                        "Error Inesperado", JOptionPane.ERROR_MESSAGE, 150, 150);
                }
            } catch (SQLException e) {
                u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraError.png",
                        "¡Hubo un error inesperado!",
                        "Error al guardar: " + e.getMessage(),
                        "Error Inesperado", JOptionPane.ERROR_MESSAGE, 150, 150);
            }
        }
        else{
            u.generarMensajeGenerico(this, Utilidades.ERROR_FALLO,
                        "¡Hubo un error inesperado!",
                        "Error al guardar.",
                        "Error Inesperado", JOptionPane.ERROR_MESSAGE, 150, 150);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jSPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSPrecioFocusLost
        // TODO add your handling code here:
        if (jSPrecio.getValue() == null) {
            jSPrecio.setValue(0.01); // restaurar mínimo
        }
    }//GEN-LAST:event_jSPrecioFocusLost

    private void jCBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCategoriaActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSeleccionarImagenActionPerformed
        // TODO add your handling code here:
        seleccionarImagen();
        
    }//GEN-LAST:event_jBSeleccionarImagenActionPerformed

    private void seleccionarImagen() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar imagen del producto");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filter);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();

            try {
                imagenSeleccionada = Files.readAllBytes(archivo.toPath());
                
                // Mostrar vista previa
                ImageIcon icono = new ImageIcon(imagenSeleccionada);
                Image imagen = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                jLImagenMostrar.setIcon(new ImageIcon(imagen));

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "No se pudo cargar la imagen: " + e.getMessage(),
                        "Error de imagen", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSeleccionarImagen;
    private javax.swing.JComboBox<Categoria> jCBCategoria;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLCategoria;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLImagenMostrar;
    private javax.swing.JLabel jLImagenOpcional;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPrecio;
    private javax.swing.JLabel jLStock;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSPrecio;
    private javax.swing.JSpinner jSStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
