/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs.direccion;

import com.capibarashop.clases.Direccion;
import com.capibarashop.clases.TipoDireccion;
import com.capibarashop.clases.dao.DireccionDAO;
import com.capibarashop.clases.Usuario;
import com.capibarashop.clases.Utilidades;
import com.capibarashop.clases.dao.TipoDireccionDAO;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Angel Aimar
 */
public class DialogAgregarDireccion extends javax.swing.JDialog {
    
    private Utilidades u = new Utilidades();
    private Runnable onDireccionGuardada;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAgregarDireccion.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     * @param parent
     * @param modal
     */
    public DialogAgregarDireccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTiposDireccion();
        
        ImageIcon icon = new ImageIcon(getClass().getResource(Utilidades.AGREGAR_DIRECCION));
        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        jLCapibara.setIcon(new ImageIcon(img));
        
        icon = new ImageIcon(getClass().getResource(Utilidades.IMG_REPARTIDOR));
        img = icon.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        
        jLCapibaraPaquete.setIcon(new ImageIcon(img));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLCalle = new javax.swing.JLabel();
        jLCiudad = new javax.swing.JLabel();
        jLTipo = new javax.swing.JLabel();
        jTFCodigoP = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jLCapibaraPaquete = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jLEstado = new javax.swing.JLabel();
        jLCodigoP = new javax.swing.JLabel();
        jLPais = new javax.swing.JLabel();
        jTFCalle = new javax.swing.JTextField();
        jTFCiudad = new javax.swing.JTextField();
        jTFEstado = new javax.swing.JTextField();
        jTFPais = new javax.swing.JTextField();
        jCBTipo = new javax.swing.JComboBox<>();
        jLCapibara = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Agregar Direccion");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, -1));

        jLCalle.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLCalle.setForeground(new java.awt.Color(0, 0, 0));
        jLCalle.setText("Calle:");
        jPanel1.add(jLCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLCiudad.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLCiudad.setForeground(new java.awt.Color(0, 0, 0));
        jLCiudad.setText("Ciudad:");
        jPanel1.add(jLCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLTipo.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLTipo.setForeground(new java.awt.Color(0, 0, 0));
        jLTipo.setText("Tipo:");
        jPanel1.add(jLTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(jTFCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 220, -1));

        jBGuardar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 130, -1));
        jPanel1.add(jLCapibaraPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 90, 90));

        jBCancelar.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, -1));

        jLEstado.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(0, 0, 0));
        jLEstado.setText("Estado:");
        jPanel1.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLCodigoP.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLCodigoP.setForeground(new java.awt.Color(0, 0, 0));
        jLCodigoP.setText("Codigo Postal:");
        jPanel1.add(jLCodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLPais.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLPais.setForeground(new java.awt.Color(0, 0, 0));
        jLPais.setText("Pais:");
        jPanel1.add(jLPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));
        jPanel1.add(jTFCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 80, 280, -1));
        jPanel1.add(jTFCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 280, -1));
        jPanel1.add(jTFEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 280, -1));
        jPanel1.add(jTFPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 160, -1));

        jCBTipo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoActionPerformed(evt);
            }
        });
        jPanel1.add(jCBTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 170, 30));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        guardarDireccion();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoActionPerformed

    private void guardarDireccion() {
        String calle = jTFCalle.getText().trim();
        String ciudad = jTFCiudad.getText().trim();
        String estado = jTFEstado.getText().trim();
        String cp = jTFCodigoP.getText().trim();
        String pais = jTFPais.getText().trim();
        TipoDireccion tipo = (TipoDireccion) jCBTipo.getSelectedItem(); 

        if (calle.isEmpty() || ciudad.isEmpty() || estado.isEmpty() || cp.isEmpty() || pais.isEmpty() || tipo == null || tipo.getId() == 0) {
            u.generarMensajeGenerico(this, Utilidades.FALTAN_CAMPOS,
                "Hay campos vacíos",
                "Por favor, rellena todos los campos",
                "Campos vacíos", JOptionPane.ERROR_MESSAGE, 150, 150);
            return;
        }

        int idUsuario = Usuario.getUsuarioActual().getId();
        DireccionDAO dao = new DireccionDAO();

        dao.marcarTodasNoPrincipal(idUsuario);

        Direccion direccion = new Direccion(idUsuario, calle, ciudad, estado, cp, pais, tipo, true);

        if (dao.insertar(direccion)) {
            u.generarMensajeGenerico(this, Utilidades.EXITO_PROCESO_GENERICO,
                "Dirección añadida como principal",
                "La nueva dirección ha sido guardada y marcada como principal",
                "Éxito", JOptionPane.INFORMATION_MESSAGE, 150, 150);
            dispose();
            if (onDireccionGuardada != null) {
                onDireccionGuardada.run();
            }
        } else {
            u.generarMensajeGenerico(this, Utilidades.ERROR_FALLO,
                "Error al guardar",
                "No se pudo guardar la dirección",
                "Error", JOptionPane.ERROR_MESSAGE, 150, 150);
        }
    }
    
    public void setOnDireccionGuardada(Runnable onDireccionGuardada) {
        this.onDireccionGuardada = onDireccionGuardada;
    }
    
    private void cargarTiposDireccion() {
        TipoDireccionDAO dao = new TipoDireccionDAO();
        List<TipoDireccion> tipos = dao.obtenerTodos();

        jCBTipo.removeAllItems();
        jCBTipo.addItem(new TipoDireccion(0, "Selecciona un tipo..."));
        
        for (TipoDireccion tipo : tipos) {
            jCBTipo.addItem(tipo);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<TipoDireccion> jCBTipo;
    private javax.swing.JLabel jLCalle;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLCapibaraPaquete;
    private javax.swing.JLabel jLCiudad;
    private javax.swing.JLabel jLCodigoP;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLPais;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFCalle;
    private javax.swing.JTextField jTFCiudad;
    private javax.swing.JTextField jTFCodigoP;
    private javax.swing.JTextField jTFEstado;
    private javax.swing.JTextField jTFPais;
    // End of variables declaration//GEN-END:variables
}
