/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs.direccion;

import com.capibarashop.clases.Direccion;
import com.capibarashop.clases.Usuario;
import com.capibarashop.clases.Utilidades;
import com.capibarashop.clases.dao.DireccionDAO;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;

//DialogActualizarProducto

/**
 *
 * @author Angel Aimar
 */
public class DialogSeleccionarDireccion extends javax.swing.JDialog {
    
    private Direccion direccionSeleccionada;
    private Utilidades u = new Utilidades();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogSeleccionarDireccion.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     */
    public DialogSeleccionarDireccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource(Utilidades.SELECCIONAR_DIRECCION));
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jLCapibara.setIcon(new ImageIcon(img));
        
        setLocationRelativeTo(getParent());
        cargarDirecciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jBSeleccionar = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jCBDirecciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 20)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Seleccionar Direccion");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, -1));

        jBSeleccionar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBSeleccionar.setText("Seleccionar");
        jBSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jBSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 100));

        jBCancelar.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, -1));

        jPanel1.add(jCBDirecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSeleccionarActionPerformed
       
    }//GEN-LAST:event_jBSeleccionarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        direccionSeleccionada = null;
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void cargarDirecciones() {
        DireccionDAO dao = new DireccionDAO();
        List<Direccion> lista = dao.listarPorUsuario(Usuario.getUsuarioActual().getId());

        jCBDirecciones.removeAllItems();

        for (Direccion d : lista) {
            jCBDirecciones.addItem(d);
        }

        // Establecer como seleccionada la dirección principal
        Direccion principal = dao.obtenerDireccionPrincipal(Usuario.getUsuarioActual().getId());
        if (principal != null) {
            for (int i = 0; i < jCBDirecciones.getItemCount(); i++) {
                Direccion item = jCBDirecciones.getItemAt(i);
                if (item.getId() == principal.getId()) {
                    jCBDirecciones.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
    
    public Direccion getDireccionSeleccionada() {
        return (Direccion) jCBDirecciones.getSelectedItem();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSeleccionar;
    private javax.swing.JComboBox<Direccion> jCBDirecciones;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
