/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs.categoria;

import com.capibarashop.dialogs.categoria.DialogActualizarCategoria;
import com.capibarashop.clases.Categoria;
import com.capibarashop.clases.dao.CategoriaDAO;
import com.capibarashop.clases.Utilidades;
import java.awt.Image;
import java.util.Comparator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//DialogActualizarProducto

/**
 *
 * @author Angel Aimar
 */
public class DialogActualizarCategoriaBuscar extends javax.swing.JDialog {
    
    private Utilidades u = new Utilidades();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogActualizarCategoriaBuscar.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     */
    public DialogActualizarCategoriaBuscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource(Utilidades.ACTUALIZAR_PRODUCTO));
        Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        jLCapibara.setIcon(new ImageIcon(img));
        
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> categorias = dao.listarCategorias();
        Categoria categoriaInicial = new Categoria(0, "Selecciona 1 para actualizar");
            Utilidades.cargarJComboBox(
            jCBCategoria,                  
            categorias,                    
            categoriaInicial,              
            Comparator.comparing(Categoria::getId), 
            "Selecciona 1 para actualizar"        
            );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jCBCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 22)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Modificar Categoria");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 200, -1));

        jBBuscar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBBuscar.setText("Modificar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 120, 120));

        jBCancelar.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 230, 90, -1));

        jPanel1.add(jCBCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        
        Categoria categoria = (Categoria) jCBCategoria.getSelectedItem();
        
        if (categoria == null || categoria.getId() == 0) {
            u.generarMensajeGenerico(this, Utilidades.ERROR_FALLO,
                    "¡La categoria: " + categoria.toString() + " no existe o no se encontró!",
                    "No existe esa categoria, Selecciona una categoria valida por favor",
                    "Seleccionar Categoria", JOptionPane.INFORMATION_MESSAGE, 150, 150);
            return;
        }
        
        DialogActualizarCategoria dialog = new DialogActualizarCategoria(null, true, categoria);
        dialog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox<Categoria> jCBCategoria;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}