/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs.categoria;

import com.capibarashop.clases.dao.CategoriaDAO;
import com.capibarashop.clases.Categoria;
import com.capibarashop.clases.Utilidades;
import java.awt.Image;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel Aimar
 */
public class DialogAgregarCategoria extends javax.swing.JDialog {
    
    private Utilidades u = new Utilidades();
    private Categoria categoria;
    private CategoriaDAO dao = new CategoriaDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAgregarCategoria.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     * @param parent
     * @param modal
     */
    public DialogAgregarCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Utilidades.aplicarScrollCombo(jCBCategoria);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/capibarashop/resources/capibaraAddProduct.png"));
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        jLCapibara.setIcon(new ImageIcon(img));

        cargarIDProximo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLIDCargar = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jLIDT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Actualizar Categoria");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 5, 210, -1));

        jLIDCargar.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLIDCargar.setForeground(new java.awt.Color(0, 0, 0));
        jLIDCargar.setText("(ID)");
        jPanel1.add(jLIDCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 60, -1));
        jPanel1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 330, -1));

        jBGuardar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 130, -1));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, 100));

        jBCancelar.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 30));

        jLNombre.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre.setText("Nombre:");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLIDT.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLIDT.setForeground(new java.awt.Color(0, 0, 0));
        jLIDT.setText("ID:");
        jPanel1.add(jLIDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cargarIDProximo() {
        jLIDCargar.setText(Integer.toString(dao.obtenerProximoIdCategoria()));
    }

    private void guardarCambios() throws SQLException {
        String nombre = jTFNombre.getText();

        if (nombre.isBlank()) {
            u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraFaltanCampos.png",
                "¡Falta ponerle el nombre a la categoria!", "Ponle un nombre categoria numero " + dao.obtenerProximoIdCategoria() + " que estará en el sistema", "Error", JOptionPane.ERROR_MESSAGE, 120, 120);
            return;
        }
        
        if (dao.existeCategoriaConNombre(nombre)) {
            u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraError.png",
                "¡Nombre duplicado!",
                "Ya existe una categoría con el nombre \"" + nombre + "\".",
                "Nombre en uso", JOptionPane.WARNING_MESSAGE, 120, 120);
            return;
        }
        
        if (categoria == null) {
            categoria = new Categoria();
        }
        
        categoria.setNombre(nombre);
        
        CategoriaDAO dao = new CategoriaDAO();
        if (dao.insertarCategoria(categoria)) {
            u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraExito.png",
                "¡Categoria nueva Agregada!", "La categoria a sido Agregada con éxito", "Agregada", JOptionPane.INFORMATION_MESSAGE, 120, 120);
            this.dispose();
        } else {
            u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraError.png",
                "¡Error al agregar!", "Ocurrió un error al guardar los cambios.", "Error", JOptionPane.ERROR_MESSAGE, 120, 120);
        }
    }
 
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            // TODO add your handling code here:
            guardarCambios();
        } catch (SQLException ex) {
            System.getLogger(DialogAgregarCategoria.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLIDCargar;
    private javax.swing.JLabel jLIDT;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
