/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs;

import com.capibarashop.clases.CategoriaDAO;
import com.capibarashop.clases.Categoria;
import com.capibarashop.clases.Producto;
import com.capibarashop.clases.ProductoDAO;
import com.capibarashop.clases.Usuario;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.JSpinner;
import java.util.List;

/**
 *
 * @author Angel Aimar
 */
public class DialogActualizarProductoBuscar extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogActualizarProductoBuscar.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     */
    public DialogActualizarProductoBuscar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/capibarashop/resources/capibaraEliminateProduct.png"));
        Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        jLCapibara.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jSIdProducto = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Eliminar Producto");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, -1));

        jLNombre.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre.setText("ID:");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jBBuscar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, -1));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 120));
        jPanel1.add(jSIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 100, -1));
        jSIdProducto.setModel(new SpinnerNumberModel(0, 0, 999999, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        // TODO add your handling code here:
        int id = (Integer) jSIdProducto.getValue();
        
        Producto p = null;
        
        ProductoDAO dao = new ProductoDAO();
        if(Usuario.getUsuarioActual().getId() == 1){
            p = dao.buscarProductoIDAdmin(id);
        }
        else{
            p = dao.buscarProductoIDyUsuario(id, Usuario.getUsuarioActual().getId());
        }
        
        if (p == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el producto con ID: " + id);
            return;
        }

        
        String mensaje = "¿Deseas eliminar el siguiente producto?\n\n" +
                         "ID: " + p.getId() + "\n" +
                         "Nombre: " + p.getNombre() + "\n" +
                         "Precio: $" + p.getPrecio() + "\n" +
                         "Stock: " + p.getStock() + "\n" +
                         "Descripción: " + p.getDescripcion();

        int confirmacion = JOptionPane.showConfirmDialog(this, mensaje, "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            if (dao.eliminarProducto(p.getId())) {
                JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente.");
                dispose(); // o limpiar campos si prefieres
                
            } else {
                JOptionPane.showMessageDialog(this, "No se elimino el producto");
            }
        }
        
        
    }//GEN-LAST:event_jBBuscarActionPerformed

   private void cargarProducto(){
       
   } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSIdProducto;
    // End of variables declaration//GEN-END:variables
}
