/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.capibarashop.dialogs;

import com.capibarashop.clases.CategoriaDAO;
import com.capibarashop.clases.Categoria;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.JSpinner;
import java.util.List;

/**
 *
 * @author Angel Aimar
 */
public class DialogAgregarProducto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogAgregarProducto.class.getName());

    /**
     * Creates new form DialogAgregarProducto
     */
    public DialogAgregarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/capibarashop/resources/capibaraAddProduct.png"));
        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        jLCapibara.setIcon(new ImageIcon(img));
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLCategoria = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLPrecio = new javax.swing.JLabel();
        jLStock = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jCBCategoria = new javax.swing.JComboBox<>();
        jTFNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jBGuardar = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jSStock = new javax.swing.JSpinner();
        jSPrecio = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLTitulo.setText("Agregar Nuevo Producto");
        jPanel1.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, -1));

        jLCategoria.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jLCategoria.setText("Categoria:");
        jPanel1.add(jLCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLNombre.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre.setText("Nombre:");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLPrecio.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLPrecio.setForeground(new java.awt.Color(0, 0, 0));
        jLPrecio.setText("Precio:");
        jPanel1.add(jLPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLStock.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLStock.setForeground(new java.awt.Color(0, 0, 0));
        jLStock.setText("Stock:");
        jPanel1.add(jLStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLDescripcion.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jLDescripcion.setText("Descripcion:");
        jPanel1.add(jLDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jPanel1.add(jCBCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 316, 170, 30));
        jPanel1.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 280, -1));

        jTADescripcion.setColumns(20);
        jTADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTADescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, 130));

        jBGuardar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));
        jPanel1.add(jLCapibara, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));
        jPanel1.add(jSStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, -1));
        jSStock.setModel(new SpinnerNumberModel(0, 0, 10000, 1));

        jSPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSPrecioFocusLost(evt);
            }
        });
        jPanel1.add(jSPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));
        jSPrecio.setModel(new SpinnerNumberModel(0, 0.00, 999999.99, 0.01));
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(jSPrecio, "$#,##0.00");
        jSPrecio.setEditor(editor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        
        Categoria categoria = (Categoria) jCBCategoria.getSelectedItem();
        
        if (jTFNombre.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
            return;
        }
        
        if(((Integer) jSStock.getValue() <= 0)){
            JOptionPane.showMessageDialog(this, "El Stock tiene que ser mayor a 0");
            return;
        }
        
        if(((Double) jSPrecio.getValue() <= 0.00)){
            JOptionPane.showMessageDialog(this, "El Precio tiene que ser mayor a $0.00");
            return;
        }
        
        if(jTADescripcion.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "El Campo Descripción es obligatorio");
            return;
        }
        
        if (categoria == null || categoria.getId() == 0) {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una categoría válida.");
            return;
        }
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void cargarCategorias(){
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> categorias = dao.listarCategorias();

        jCBCategoria.removeAllItems();
        jCBCategoria.addItem(new Categoria(0, "Selecciona una categoría..."));

        for (Categoria c : categorias) {
            jCBCategoria.addItem(c);
        }
        
    }
    
    private void jSPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSPrecioFocusLost
        // TODO add your handling code here:
        if (jSPrecio.getValue() == null) {
            jSPrecio.setValue(0.01); // restaurar mínimo
        }
    }//GEN-LAST:event_jSPrecioFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogAgregarProducto dialog = new DialogAgregarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<Categoria> jCBCategoria;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLCategoria;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPrecio;
    private javax.swing.JLabel jLStock;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSPrecio;
    private javax.swing.JSpinner jSStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
