/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.capibarashop.swin;

import com.capibarashop.clases.Usuario;
import com.capibarashop.clases.UsuarioDAO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Image;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import com.capibarashop.clases.Utilidades;

/**
 *
 * @author Angel Aimar
 */
public class P_Login extends javax.swing.JPanel {
    
    private Utilidades u = new Utilidades();
    
    /**
     * Creates new form P_Login
     */
    public P_Login() {
        initComponents(); //570, 430
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/capibarashop/resources/capibara.png"));
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        jLCapibara.setIcon(new ImageIcon(img));
        this.setPreferredSize(new java.awt.Dimension(570, 430));
//        this.setLayout(new BorderLayout());
//        this.add(new P_Login(), BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLCapibara = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jFondoColor = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("User Name");

        jLabel4.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel1.setFont(new java.awt.Font("STXinwei", 0, 48)); // NOI18N
        jLabel1.setText("Login");

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setPreferredSize(new java.awt.Dimension(70, 26));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel2.setText("User Name");

        jButtonLogin.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseExited(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jLCapibara.setMaximumSize(new java.awt.Dimension(150, 150));
        jLCapibara.setMinimumSize(new java.awt.Dimension(50, 50));
        jLCapibara.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRegister.setForeground(new java.awt.Color(153, 255, 255));
        jLabelRegister.setText("Register");
        jLabelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRegisterMouseExited(evt);
            }
        });

        jFondoColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/capibarashop/resources/fondo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLCapibara, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabelRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFondoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLCapibara, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabelRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFondoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseClicked
        // TODO add your handling code here:
        Container parent = this.getParent();

        try {
            Panel_Login_Register.cambiarContenido(parent, 2);
        } catch (SQLException e) {
            e.printStackTrace();
            u.generarMensajeGenerico(parent, "/com/capibarashop/resources/capibaraError.png",
            "¡Hubo un error inesperado!",
            "Error al cargar el Registro: " + e.getMessage(),
            "Error Inesperado",JOptionPane.ERROR_MESSAGE, 120, 120);
        }
        parent.revalidate();
        parent.repaint();
    }//GEN-LAST:event_jLabelRegisterMouseClicked

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        String user = txtUserName.getText().trim();
        String pass = new String(txtPass.getPassword()).trim();
        
        UsuarioDAO dao = new UsuarioDAO();
        
        try {
            Usuario nuevo = dao.login(user, pass);
            if (nuevo != null) {
                u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraCliente.png", "¡Bienvenido " + nuevo.getNombre() + "!", 
                        "Espero que tengas una buena estadia en CapibaraShop, disfrutalo", "Bienvenida", JOptionPane.INFORMATION_MESSAGE, 120, 120);
                Usuario.setUsuarioActual(nuevo);
                //JOptionPane.showMessageDialog(this, "El id del usuario es: " + Usuario.getUsuarioActual().getId());
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                frame.dispose();
                
                String rol = nuevo.getRol().toString();
                
                if(rol.equalsIgnoreCase("Administrador") || rol.equalsIgnoreCase("Vendedor")){
                    //Admin o Vendedor

                    JFrame main;
                    
                    if(rol.equalsIgnoreCase("Administrador"))
                    main = new JFrame("Panel de Productos Admin");
                    else
                    main = new JFrame("Panel de Productos del vendedor");
                    
                    main.setContentPane(new P_ProductosAdmin());
                    main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    main.setSize(890, 600);
                    main.setVisible(true);
                }
                else if(rol.equalsIgnoreCase("Cliente")){
                    //Clientes
                    
                    JFrame main = new JFrame("Panel de Productos Cliente");

                }

            } else {
                u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraError.png",
                    "¡Hubo un error inesperado!",
                    "Error al iniciar sesion",
                    "Error Inesperado", JOptionPane.ERROR_MESSAGE, 120, 120);
            }
        } catch (SQLException e) {
            u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraError.png",
                    "¡Hubo un error inesperado!",
                    "Error al iniciar sesion: " + e.getMessage(),
                    "Error Inesperado", JOptionPane.ERROR_MESSAGE, 120, 120);
        }

    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
        jButtonLogin.doClick();
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // ODO add your handling code here:
        txtPass.requestFocusInWindow();
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void jLabelRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseEntered
        // TODO add your handling code here:
        jLabelRegister.setBackground(new Color(100, 100, 255));
        jLabelRegister.setForeground(Color.white);
        jLabelRegister.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelRegisterMouseEntered

    private void jLabelRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegisterMouseExited
        // TODO add your handling code here:
        jLabelRegister.setBackground(new Color(30, 30, 30));     // Color original
        jLabelRegister.setForeground(new Color(153, 255, 255));
        jLabelRegister.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelRegisterMouseExited

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        // TODO add your handling code here:
        jButtonLogin.setBackground(new Color(180, 180, 180)); 
        jButtonLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonLoginMouseEntered

    private void jButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseExited
        // TODO add your handling code here:
        jButtonLogin.setBackground(new Color(204, 204, 204));  
        jButtonLogin.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonLoginMouseExited
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jFondoColor;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelRegister;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
