/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.capibarashop.swin;

import com.capibarashop.clases.CategoriaDAO;
import com.capibarashop.clases.Producto;
import com.capibarashop.clases.ProductoDAO;
import com.capibarashop.clases.Usuario;
import com.capibarashop.dialogs.DialogAgregarProducto;
import com.capibarashop.dialogs.DialogEliminarProducto;
import java.awt.Image;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel Aimar
 */
public class P_ProductosAdmin extends javax.swing.JPanel {
    
    /**
     * Creates new form P_ProductosAdmin
     */
    public P_ProductosAdmin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jTPGeneral = new javax.swing.JTabbedPane();
        jPMostrarProductos = new javax.swing.JPanel();
        jScrollPaneTablaProductos = new javax.swing.JScrollPane();
        jTPaneProductos = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jBActualizarL = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jPCategorias = new javax.swing.JPanel();
        jCapibaraLogo = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPaneTablaProductos.setViewportView(jTPaneProductos);
        jTPaneProductos.setEditable(false);

        jBActualizarL.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBActualizarL.setText("Actualizar Lista");
        jBActualizarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarLActionPerformed(evt);
            }
        });

        jBAgregar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBAgregar.setText("Agregar Producto");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBEliminar.setFont(new java.awt.Font("STXinwei", 0, 24)); // NOI18N
        jBEliminar.setText("Eliminar Producto");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAgregar)
                .addGap(126, 126, 126)
                .addComponent(jBEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jBActualizarL)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBActualizarL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPMostrarProductosLayout = new javax.swing.GroupLayout(jPMostrarProductos);
        jPMostrarProductos.setLayout(jPMostrarProductosLayout);
        jPMostrarProductosLayout.setHorizontalGroup(
            jPMostrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneTablaProductos)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPMostrarProductosLayout.setVerticalGroup(
            jPMostrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMostrarProductosLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneTablaProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );

        jTPGeneral.addTab("Mis Productos", jPMostrarProductos);

        javax.swing.GroupLayout jPCategoriasLayout = new javax.swing.GroupLayout(jPCategorias);
        jPCategorias.setLayout(jPCategoriasLayout);
        jPCategoriasLayout.setHorizontalGroup(
            jPCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPCategoriasLayout.setVerticalGroup(
            jPCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jTPGeneral.addTab("Categorias", jPCategorias);

        jLUsuario.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLUsuario.setText("Bienvenido Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPGeneral)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCapibaraLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCapibaraLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jLUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jTPGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBActualizarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarLActionPerformed
        ProductoDAO dao = new ProductoDAO();
        
        try {
            List<Producto> productos;
            if(Usuario.getUsuarioActual().getId() == 1){
                productos = dao.listarProductosAdmin();
            }
            else{
               productos = dao.listarProductosPorUsuario(Usuario.getUsuarioActual().getId());
            }
            
            listarMisProductos(productos);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al recargar productos.");
        }
    }//GEN-LAST:event_jBActualizarLActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        DialogAgregarProducto dialog = new DialogAgregarProducto(null, true);
        dialog.setVisible(true);
        
        ProductoDAO dao = new ProductoDAO();
                    
        try {
            List<Producto> productos;
            if(Usuario.getUsuarioActual().getId() == 1){
                productos = dao.listarProductosAdmin();
            }
            else{
               productos = dao.listarProductosPorUsuario(Usuario.getUsuarioActual().getId());
            }
            
            listarMisProductos(productos);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al recargar productos.");
        }
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        DialogEliminarProducto dialog = new DialogEliminarProducto(null, true);
        dialog.setVisible(true);
        
        ProductoDAO dao = new ProductoDAO();
        
        try {
            List<Producto> productos;
            if(Usuario.getUsuarioActual().getId() == 1){
                productos = dao.listarProductosAdmin();
            }
            else{
               productos = dao.listarProductosPorUsuario(Usuario.getUsuarioActual().getId());
            }
            
            listarMisProductos(productos);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al recargar productos.");
        }
        
    }//GEN-LAST:event_jBEliminarActionPerformed

    public void listarMisProductos(List<Producto> productos){
        StringBuilder sb = new StringBuilder();
        
        sb.append("""
                  <html>
                        <head>
                          <style>
                            h1 {
                                text-align: center;
                                color: #4273b9;
                            }
                            table, th, td {
                                border: 1px solid gray;
                                border-collapse: collapse;
                            }
                            th {
                                background-color: #2a4a89;
                                color: white;
                            }
                            td {
                                padding: 5px;
                                max-width: 200px;
                                word-wrap: break-word;
                                white-space: normal;
                                overflow-wrap: break-word;
                                word-break: break-all;
                                text-align: left;
                                vertical-align: top;
                            }
                            table {
                                width: 100%;
                            }
                  
                            .desc {
                              max-height: 60px;
                              overflow-y: auto;
                              overflow-x: hidden;
                              word-wrap: break-word;
                              white-space: normal;
                            }
                            
                          </style>
                        </head>
                    <body>
                    <h1>Mis Productos</h1>
                    <table>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Precio</th>
                            <th>Stock</th>
                            <th>Descripción</th>
                            <th>Categoría</th>
                        </tr>
                  """);
        
        for(Producto p : productos){
            sb.append("<tr>");
            sb.append("<td>").append(p.getId()).append("</td>");
            sb.append("<td>").append(p.getNombre()).append("</td>");
            sb.append("<td>").append(p.getPrecio()).append("</td>");
            sb.append("<td>").append(p.getStock()).append("</td>");
            sb.append("<td> <div class=\"desc\">").append(p.getDescripcion()).append(" </div> </td>");
            sb.append("<td>").append(p.getNombreCategoria()).append("</td>");
            sb.append("</tr>");
        }
        
        sb.append("""
                </table>
            </body>
        </html>
        """);
        
        jTPaneProductos.setContentType("text/html");
        jTPaneProductos.setText(sb.toString());
        jTPaneProductos.setCaretPosition(0); // Regresa al inicio visual
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarL;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JLabel jCapibaraLogo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPCategorias;
    private javax.swing.JPanel jPMostrarProductos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneTablaProductos;
    private javax.swing.JTabbedPane jTPGeneral;
    private javax.swing.JTextPane jTPaneProductos;
    // End of variables declaration//GEN-END:variables
}
