/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.capibarashop.swin;

import com.capibarashop.clases.Rol;
import com.capibarashop.clases.Usuario;
import com.capibarashop.clases.UsuarioDAO;
import com.capibarashop.clases.Utilidades;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Image;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Angel Aimar
 */
public class P_Register extends javax.swing.JPanel {
    
    private Utilidades u = new Utilidades();
    
    /**
     * Creates new form P_Login
     * @throws java.sql.SQLException
     */
    public P_Register() throws SQLException {
        initComponents();
        cargarRoles();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/capibarashop/resources/capibara.png"));
        Image img = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH); // ← Ajusta tamaño aquí
        jLCapibara.setIcon(new ImageIcon(img));
        this.setPreferredSize(new java.awt.Dimension(570, 430));
//        try {
//            cargarRoles();
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(this, "Error al cargar roles: " + e.getMessage());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLRegister = new javax.swing.JLabel();
        jLUserName = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        txtPass1 = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbRol = new javax.swing.JComboBox<>();
        jFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLCapibara = new javax.swing.JLabel();
        jFondoColor = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("User Name");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLRegister.setFont(new java.awt.Font("STXinwei", 0, 48)); // NOI18N
        jLRegister.setText("Register");

        jLUserName.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLUserName.setText("User Name");

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setForeground(new java.awt.Color(0, 0, 0));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        jButtonRegister.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jButtonRegister.setText("Registrarse");
        jButtonRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRegisterMouseExited(evt);
            }
        });
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        txtPass1.setBackground(new java.awt.Color(255, 255, 255));
        txtPass1.setForeground(new java.awt.Color(0, 0, 0));
        txtPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass1ActionPerformed(evt);
            }
        });

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(153, 255, 255));
        jLabelLogin.setText("Regresar al Login");
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel5.setText("Password Again");

        txtPass2.setBackground(new java.awt.Color(255, 255, 255));
        txtPass2.setForeground(new java.awt.Color(0, 0, 0));
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel6.setText("Nombre Completo");

        jLabel7.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel7.setText("Telefono");

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel8.setText("E-mail");

        txtTel.setBackground(new java.awt.Color(255, 255, 255));
        txtTel.setForeground(new java.awt.Color(0, 0, 0));
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel9.setText("Rol");

        jcbRol.setBackground(new java.awt.Color(255, 255, 255));
        jcbRol.setFont(new java.awt.Font("STXinwei", 0, 14)); // NOI18N
        jcbRol.setForeground(new java.awt.Color(0, 0, 0));
        jcbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRolActionPerformed(evt);
            }
        });

        jFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        jFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("STXinwei", 0, 18)); // NOI18N
        jLabel10.setText("Fecha Nacimiento");

        jFondoColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/capibarashop/resources/fondo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jcbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLCapibara, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabelLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLUserName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addComponent(jFondoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jcbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLCapibara, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabelLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(txtPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jFondoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // ODO add your handling code here:
        txtNombre.requestFocusInWindow();
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass1ActionPerformed
        // TODO add your handling code here:
        txtPass2.requestFocusInWindow();
    }//GEN-LAST:event_txtPass1ActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        String usuario = txtUser.getText().trim();
        String nombre = txtNombre.getText().trim();
        String pass1 = txtPass1.getText().trim();
        String pass2 = txtPass2.getText().trim();
        String email = txtEmail.getText().trim();
        String tel = txtTel.getText().trim();
        Rol rol = (Rol) jcbRol.getSelectedItem();
        
        // Validaciones
        if (usuario.isEmpty() || nombre.isEmpty() || pass1.isEmpty() || pass2.isEmpty() || email.isEmpty() || 
                jFechaNacimiento.getDate() == null ||tel.isEmpty()) {
            
            u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraFaltanCampos.png",
                    "¡Falta campos!",
                    "Revisa que campos faltan para agregarlos",
                    "Registro", JOptionPane.INFORMATION_MESSAGE, 150, 150);
            return;
        }
        
        //Se colocan aqui por si no han colocado alguna variable para que no lance error
        java.util.Date fechaN = jFechaNacimiento.getDate(); //Este es una variable de transicion
        Date fechaNacimiento = new java.sql.Date(fechaN.getTime());
        
        if (!pass1.equals(pass2)) {
            
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            return;
        }

        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(this, "El correo no es válido.");
            return;
        }

        if (tel.length() != 10 || !tel.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "El teléfono debe tener 10 dígitos numéricos.");
            return;
        }

        if (rol == null || rol.getId() == 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un rol válido.");
            return;
        }
        
        // Crear el usuario e insertarlo
        Usuario nuevo = new Usuario(usuario, nombre, pass1, email, fechaNacimiento, tel, rol.getId());

        UsuarioDAO dao = new UsuarioDAO();

        if(dao.usuarioExiste(usuario)) {
            JOptionPane.showMessageDialog(this, "El nombre de usuario ya está en uso. Elige otro.");
            return;
        }

        if (dao.emailExiste(email)) {
            JOptionPane.showMessageDialog(this, "Este correo ya está registrado. Usa uno diferente.");
            return;
        }
        
        if(rol.getId() == 0){
            JOptionPane.showMessageDialog(this, "Selecciona un rol valido");
            return;
        }
        
        try {
            if (dao.insertarUsuario(nuevo)) {
                u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraRegistroCorrecto.png",
                    "¡Felicidades te has registrado correctamente!",
                    "Felicidades, ya tienes una cuenta aqui en CapibaraShop, disfruta de tu cuenta",
                    "Registro", JOptionPane.INFORMATION_MESSAGE, 120, 120);
                
                this.removeAll();
                this.setLayout(new BorderLayout());
                this.add(new P_Login(), BorderLayout.CENTER); // ← tu panel de logeo
                this.revalidate();
                this.repaint();
                
                // Puedes regresar al login si quieres aquí
            } else {
                u.generarMensajeGenerico(this, "/com/capibarashop/resources/capibaraError.png",
                    "¡Hubo un error inesperado!",
                    "No se pudo realizar el registro correctamente",
                    "Error Inesperado", JOptionPane.ERROR_MESSAGE, 120, 120);
            }   
        } catch (SQLException ex) {
            System.getLogger(P_Register.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void cargarRoles(){
        UsuarioDAO dao = new UsuarioDAO();
        List<Rol> roles;
        
        try {
            roles = dao.obtenerRoles();
            jcbRol.removeAllItems();
            jcbRol.addItem(new Rol(0, "Elegir"));
        
            for(Rol rol : roles){
                jcbRol.addItem(rol);
            }
        } catch (SQLException ex) {
            System.getLogger(P_Register.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
   
    
    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        // TODO add your handling code here:
        Container parent = this.getParent();

        // Limpiar y cargar el nuevo panel
        parent.removeAll();
        try {
            Panel_Login_Register.cambiarContenido(parent,1);
        } catch (SQLException ex) {
            System.getLogger(P_Register.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jLabelLoginMouseClicked

    
    
    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed
        // TODO add your handling code here:
        txtEmail.requestFocusInWindow();
    }//GEN-LAST:event_txtPass2ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        txtTel.requestFocusInWindow();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        txtPass1.requestFocusInWindow();
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
        jcbRol.requestFocusInWindow();
    }//GEN-LAST:event_txtTelActionPerformed

    private void jcbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRolActionPerformed

    private void jLabelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseEntered
        // TODO add your handling code here:
        jLabelLogin.setBackground(new Color(100, 100, 255));
        jLabelLogin.setForeground(Color.white);
        jLabelLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelLoginMouseEntered

    private void jLabelLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseExited
        // TODO add your handling code here:
        jLabelLogin.setBackground(new Color(30, 30, 30));     // Color original
        jLabelLogin.setForeground(new Color(153, 255, 255));
        jLabelLogin.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelLoginMouseExited

    private void jButtonRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseEntered
        // TODO add your handling code here:
        jButtonRegister.setBackground(new Color(180, 180, 180));   
        jButtonRegister.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonRegisterMouseEntered

    private void jButtonRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegisterMouseExited
        // TODO add your handling code here:
        jButtonRegister.setBackground(new Color(204, 204, 204));  
        jButtonRegister.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonRegisterMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonRegister;
    private com.toedter.calendar.JDateChooser jFechaNacimiento;
    private javax.swing.JLabel jFondoColor;
    private javax.swing.JLabel jLCapibara;
    private javax.swing.JLabel jLRegister;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Rol> jcbRol;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass1;
    private javax.swing.JTextField txtPass2;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
